# Generated by Django 6.1.1 on 2026-10-08 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_patient_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(default='TEMP', help_text='Hospital or clinic registration number', max_length=30, unique=True, verbose_name='Patient ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='designation',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('nurse', 'Nurse'), ('midwife', 'Midwife'), ('senior_health_worker', 'Senior Health Worker')], default='nurse', max_length=30),
        ),
        migrations.AddField(
            model_name='visit',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_visits', to=settings.AUTH_USER_MODEL),
        ),
    ]
